```{r, echo = FALSE}
title <- "temp_name"
```

---
title: `r title`
author: "Steffan Noe Niikanoff Christiansen"
output: html_document
---


### Global options and paths
```{r Global options and paths, echo = FALSE, message=FALSE}
# libraries
packages <- c("tidyverse", "patchwork", "kableExtra", "noecodedup", "here", "knitr")

invisible(lapply(packages, require, character.only = TRUE)) 
theme_set(theme_bw() + 
            theme(plot.title = element_text(hjust = 0.5),
                  axis.text.x = element_text(angle = 45,
                                             margin = margin(4, 0, 0, 0),
                                             hjust = 1),
                  strip.text = element_text(size = 8),
                  strip.background = element_rect(fill="white"),
                  panel.spacing = unit(0.1, "lines")))
# update_geom_defaults("vline", aes(linewidth = 0.75))

# paths
root_path <- here()
projects_path <- str_remove(root_path, "/[A-z]+$")
title <- str_replace_all(title, " ", "_")
fig_path <- here("results", "images", title, "/")
tab_path <- here("results", "tables", title, "/")

# global options
opts_knit$set(root.dir = root_path)
opts_chunk$set(message = FALSE,
               dpi = 300,
               dev = "jpeg",
               fig.width = 6,
               fig.height = 6,
               fig.align="center", 
               fig.path = fig_path,
               echo = FALSE,
               warning = FALSE)

options(scipen = 100, digits = 3, bitmapType = "cairo") # fixes grid.Call warning 
time <- lubridate::date()
```

Rendering of the report was started `r time` <br> Following packages
were loaded: `r packages` <br><br>


#### Data
```{r Data}
# list.files(data_path, pattern = "csv")

# readme <- read_tsv(file.path(data_path, "README.txt"), col_names = c("README"))
# readme %>% 
#   kable() %>% 
#   kable_minimal()
```
<br>

List: <br> 

  1) A
  2) B
  3) C


#### Unresolved questions
List: <br> 

  * A 
  * B 
  * C

 <br><br> 


<br><br>

------------------------------------------------------------------------
```{r computetime, echo=FALSE}
time <- lubridate::date()
```
Report was finished `r time` <br>


```{r}
sessionInfo()
```


```{r rendering while keeping objects in global environment, echo = FALSE, eval=FALSE}
rmarkdown::render("scripts/template.Rmd", clean = TRUE, output_dir = "reports/")
```
<br>
